### ISSUE TITLE
Kitty icat doesn't properly capture fzf dimensions

### ISSUE THREAD

**Issue by prurph** [jannis-baum/fzf-dotfiles#1]
This setup is really cool!

Perhaps I somehow have different zsh expansion settings, but as written the `FZFDF_IMG` command expands the `FZF_PREVIEW_` variables when the script is sourced and they do not exist, as opposed to at runtime when fzf is invoked. Consequently image previews error with an atoi error inside kitty because the command is effectively receiving `--place=x@0x0 {}`.

I was able to fix this by escaping the dollar signs on [this line](https://github.com/jannis-baum/fzf-dotfiles/blob/3bf5f03a8731ab38e46cae0b7453889854b0ffed/options.zsh#L49) as: `\${FZF_PREVIEW_COLUMNS}x\${FZF_PREVIEW_LINES}@0x0`.

**Comment by jannis-baum** [comment]
Hey! I just saw that the problem you mentioned is actually a problem on my setup as well; I must have rushed the testing. I added your fix in the latest commit and set you as a co-author, thank you!

---

I'm happy you like the setup! If you have any feedback on how usable this is I'd be happy to hear about it since I'm trying to make my dotfiles as modular as possible but so far I'm probably the only person using them🙈

I also have some [other repos](https://github.com/stars/jannis-baum/lists/my-dotfiles) in case you are interested in them; particularly the [git-related dotfiles](https://github.com/jannis-baum/git.zsh-dotfiles) with lots of fzf-functions and [si-vim](https://github.com/jannis-baum/si-vim.zsh) if you use Vim might be interesting for you :)
